const boroughs = [
    { value: "Barking and Dagenham", isChecked: false },
    { value: "Barnet", isChecked: false },
    { value: "Bexley", isChecked: false },
    { value: "Brent", isChecked: false },
    { value: "Bromley", isChecked: false },
    { value: "Camden", isChecked: false },
    { value: "Croydon", isChecked: false },
    { value: "Ealing", isChecked: false },
    { value: "Enfield", isChecked: false },
    { value: "Barking", isChecked: false },
    { value: "Greenwich", isChecked: false },
    { value: "Hackney", isChecked: false },
    { value: "Hammersmith and Fulham", isChecked: false },
    { value: "Haringey", isChecked: false },
    { value: "Harrow", isChecked: false },
    { value: "Hounslow", isChecked: false },
    { value: "Islington", isChecked: false },
    { value: "Kensington upon Thames", isChecked: false },
    { value: "Lambeth", isChecked: false },
    { value: "Lewisham", isChecked: false },
    { value: "Merton", isChecked: false },
    { value: "Newham", isChecked: false },
    { value: "Redbridge", isChecked: false },
    { value: "Richmond upon Thames", isChecked: false },
    { value: "Southwark", isChecked: false },
    { value: "Sutton", isChecked: false },
    { value: "Tower Hamlets", isChecked: false },
    { value: "Waltham Forest", isChecked: false },
    { value: "Wandsworth", isChecked: false },
    { value: "Westminster", isChecked: false },
    { value: "City of London (33rd principal division of Greater London - not a London borough)", isChecked: false },

];

export default boroughs;
